# Generated by Django 4.2.9 on 2024-01-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_webhookissuecreated_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookissuecreated',
            name='issue_id',
            field=models.CharField(default='', max_length=255, verbose_name='Идентификатор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webhookissuecreated',
            name='project_name',
            field=models.TextField(default='', verbose_name='Название проекта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webhookissuecreated',
            name='status',
            field=models.CharField(default='', max_length=255, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
